library(tidyverse)
library(ggplot2)
library(dplyr)
library(stringr)
library(plotly)
library(rcartocolor)

dat <- read_csv("data.csv")
dat <- dat %>% select(c("countryName","eprtrSectorName","facilityName","Longitude","Latitude","City","pollutant","emissions","reportingYear"))
regions <- read_csv("regions.csv")
dat <- inner_join(dat, regions, by = "countryName")
countries <- dat %>% distinct(countryName)
